## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Port Elizabeth,ZA,-33.9180,25.5701,54.32,87,20,13.00,few clouds
1,1,Busselton,AU,-33.6500,115.3333,57.54,64,81,6.17,broken clouds
2,2,Northam,GB,51.0333,-4.2167,61.39,88,0,5.55,clear sky
3,3,Pacifica,US,37.6138,-122.4869,87.06,87,20,14.97,fog
4,4,Valverde Del Camino,ES,37.5751,-6.7543,76.03,33,0,4.25,clear sky

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 

min_temp = float(input("What is the minimum temperature you would like for your trip? "))

max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 95

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
3,3,Pacifica,US,37.6138,-122.4869,87.06,87,20,14.97,fog
4,4,Valverde Del Camino,ES,37.5751,-6.7543,76.03,33,0,4.25,clear sky
6,6,Puerto Ayora,EC,-0.7393,-90.3518,70.56,93,34,5.99,scattered clouds
7,7,Rikitea,PF,-23.1203,-134.9692,73.78,77,0,6.71,light rain
11,11,Acapulco,MX,16.8634,-99.8901,84.02,84,75,4.61,broken clouds
12,12,Butaritari,KI,3.0707,172.7902,82.13,80,42,17.74,light rain
13,13,Locri,IT,38.2414,16.2623,70.32,68,0,7.58,clear sky
14,14,Victoria,HK,22.2855,114.1577,89.65,74,73,8.99,broken clouds
15,15,Komsomolskiy,UZ,40.4272,71.7189,79.52,29,44,6.91,scattered clouds
19,19,Vaini,TO,-21.2000,-175.2000,78.96,78,40,11.50,scattered clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                353
City                   353
Country                353
Lat                    353
Lng                    353
Max Temp               353
Humidity               353
Cloudiness             353
Wind Speed             353
Current Description    353
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
3,3,Pacifica,US,37.6138,-122.4869,87.06,87,20,14.97,fog
4,4,Valverde Del Camino,ES,37.5751,-6.7543,76.03,33,0,4.25,clear sky
6,6,Puerto Ayora,EC,-0.7393,-90.3518,70.56,93,34,5.99,scattered clouds
7,7,Rikitea,PF,-23.1203,-134.9692,73.78,77,0,6.71,light rain
11,11,Acapulco,MX,16.8634,-99.8901,84.02,84,75,4.61,broken clouds
...,...,...,...,...,...,...,...,...,...,...
668,668,Mecca,SA,21.4267,39.8261,85.35,26,92,5.73,overcast clouds
669,669,Tateyama,JP,34.9833,139.8667,79.27,81,88,3.89,overcast clouds
670,670,Nador,MA,35.1740,-2.9287,73.65,83,40,2.30,scattered clouds
672,672,Marsaxlokk,MT,35.8419,14.5431,76.08,83,20,5.75,few clouds
674,674,Muromtsevo,RU,56.3724,75.2418,74.46,73,32,8.70,scattered clouds

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Pacifica,US,87.06,fog,37.6138,-122.4869,
4,Valverde Del Camino,ES,76.03,clear sky,37.5751,-6.7543,
6,Puerto Ayora,EC,70.56,scattered clouds,-0.7393,-90.3518,
7,Rikitea,PF,73.78,light rain,-23.1203,-134.9692,
11,Acapulco,MX,84.02,broken clouds,16.8634,-99.8901,
...,...,...,...,...,...,...,...
668,Mecca,SA,85.35,overcast clouds,21.4267,39.8261,
669,Tateyama,JP,79.27,overcast clouds,34.9833,139.8667,
670,Nador,MA,73.65,scattered clouds,35.1740,-2.9287,
672,Marsaxlokk,MT,76.08,few clouds,35.8419,14.5431,
674,Muromtsevo,RU,74.46,scattered clouds,56.3724,75.2418,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.

for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude to location key for the params dictionary.
    
    params["location"] = f"{lat},{lng}"

    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    

    # 6e. Make request and retrieve the JSON data from the search. 
    
    hotels = requests.get(base_url, params=params).json()
       
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    
    try:
    
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    
    except (IndexError,IndentationError):
    
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [9]:
# 7. Drop the rows where there is no Hotel Name

clean_hotel_df = hotel_df[hotel_df["Hotel Name"]!= '']
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Pacifica,US,87.06,fog,37.6138,-122.4869,"Pacifica Lighthouse, Trademark Collection by W..."
4,Valverde Del Camino,ES,76.03,clear sky,37.5751,-6.7543,HOTEL MONTEAROMA (ulamde hotelera S.L.)
6,Puerto Ayora,EC,70.56,scattered clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
7,Rikitea,PF,73.78,light rain,-23.1203,-134.9692,People ThankYou
11,Acapulco,MX,84.02,broken clouds,16.8634,-99.8901,HS Hotsson Smart Acapulco
12,Butaritari,KI,82.13,light rain,3.0707,172.7902,Isles Sunset Lodge
13,Locri,IT,70.32,clear sky,38.2414,16.2623,Grand Hotel President
14,Victoria,HK,89.65,broken clouds,22.2855,114.1577,Mini Central
15,Komsomolskiy,UZ,79.52,scattered clouds,40.4272,71.7189,Ikathouse
19,Vaini,TO,78.96,scattered clouds,-21.2000,-175.2000,Keleti Beach Resort

In [10]:
# 8a. Create the output File (CSV)

output_data_file = "Weatherpy_Vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.

info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.

hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.

locations = clean_hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure()
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))